"""Catálogo de livros reais para seed (título, autor, gênero, preço, estoque, descrição)."""

from decimal import Decimal

# (titulo, autor, genero, preco, estoque, descricao)
REAL_BOOKS: list[tuple[str, str, str, str, int, str]] = [
    (
        "Dom Casmurro",
        "Machado de Assis",
        "Romance",
        "29.90",
        25,
        "Clássico da literatura brasileira sobre ciúme e memória, narrado por Bentinho.",
    ),
    (
        "Memórias Póstumas de Brás Cubas",
        "Machado de Assis",
        "Romance",
        "24.90",
        30,
        "Romance em primeira pessoa de um defunto autor, marco do realismo no Brasil.",
    ),
    (
        "O Cortiço",
        "Aluísio Azevedo",
        "Romance",
        "22.50",
        18,
        "Retrato naturalista da vida em um cortiço carioca no século XIX.",
    ),
    (
        "Capitães da Areia",
        "Jorge Amado",
        "Romance",
        "34.90",
        20,
        "História de meninos de rua em Salvador e suas lutas diárias.",
    ),
    (
        "Gabriela, Cravo e Canela",
        "Jorge Amado",
        "Romance",
        "32.00",
        22,
        "Romance de Ilhéus com Gabriela, o olhar do narrador e o cacao.",
    ),
    (
        "Grande Sertão: Veredas",
        "João Guimarães Rosa",
        "Romance",
        "45.00",
        12,
        "Epopeia linguística do sertão brasileiro narrada por Riobaldo.",
    ),
    (
        "A Hora da Estrela",
        "Clarice Lispector",
        "Romance",
        "26.90",
        28,
        "Último romance de Clarice, sobre Macabéa e a vida em Rio de Janeiro.",
    ),
    (
        "Vidas Secas",
        "Graciliano Ramos",
        "Romance",
        "23.90",
        16,
        "Drama familiar no sertão nordestino em prosa enxuta e intensa.",
    ),
    (
        "O Alienista",
        "Machado de Assis",
        "Romance",
        "18.90",
        35,
        "Novela sobre Simon Bacamarte e o hospício de Itaguaí.",
    ),
    (
        "O Quinze",
        "Rachel de Queiroz",
        "Romance",
        "21.50",
        14,
        "Romance sobre a seca de 1915 no Ceará e a migração forçada.",
    ),
    (
        "O Deserto dos Tártaros",
        "Dino Buzzati",
        "Romance",
        "31.90",
        15,
        "Drogo aguarda o inimigo na fortaleza Bastiani, em clima de suspensão existencial.",
    ),
    (
        "Assassinato no Expresso do Oriente",
        "Agatha Christie",
        "Mistério",
        "27.90",
        24,
        "Hercule Poirot investiga um crime a bordo do luxuoso trem.",
    ),
    (
        "O Xangô de Baker Street",
        "Jô Soares",
        "Mistério",
        "29.50",
        19,
        "Sherlock Holmes e dr. Watson desvendam um mistério no Rio imperial.",
    ),
    (
        "A Garota no Trem",
        "Paula Hawkins",
        "Mistério",
        "25.90",
        26,
        "Thriller psicológico sobre memória, obsessão e um desaparecimento.",
    ),
    (
        "O Homem Duplicado",
        "José Saramago",
        "Mistério",
        "28.00",
        17,
        "Tertuliano descobre um homem idêntico a si e sua vida se desorganiza.",
    ),
    (
        "O Caso da Estranha Múmia",
        "Arthur Conan Doyle",
        "Mistério",
        "19.90",
        40,
        "Contos com Sherlock Holmes reunidos para leitores de mistério clássico.",
    ),
    (
        "Fundação",
        "Isaac Asimov",
        "Ficção Científica",
        "36.90",
        21,
        "Início da saga sobre o Império Galáctico e a psicohistória de Hari Seldon.",
    ),
    (
        "Duna",
        "Frank Herbert",
        "Ficção Científica",
        "42.00",
        18,
        "Paul Atreides no planeta Arrakis, especiaria e destino político.",
    ),
    (
        "Neuromancer",
        "William Gibson",
        "Ficção Científica",
        "33.50",
        14,
        "Obra fundadora do cyberpunk com Case, IA e redes neurais.",
    ),
    (
        "O Problema dos Três Corpos",
        "Liu Cixin",
        "Ficção Científica",
        "38.90",
        16,
        "Ficção científica hard sobre civilizações e o destino da humanidade.",
    ),
    (
        "Solaris",
        "Stanislaw Lem",
        "Ficção Científica",
        "30.00",
        13,
        "Cientistas enfrentam o oceano consciente do planeta Solaris.",
    ),
    (
        "O Senhor dos Anéis: A Sociedade do Anel",
        "J.R.R. Tolkien",
        "Fantasia",
        "49.90",
        20,
        "Frodo e a Comunidade iniciam a jornada para destruir o Um Anel.",
    ),
    (
        "Harry Potter e a Pedra Filosofal",
        "J.K. Rowling",
        "Fantasia",
        "39.90",
        35,
        "Harry descobre Hogwarts, amizades e o primeiro confronto com Voldemort.",
    ),
    (
        "As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa",
        "C.S. Lewis",
        "Fantasia",
        "29.90",
        22,
        "Quatro irmãos atravessam o guarda-roupa para o mundo de Nárnia.",
    ),
    (
        "O Nome do Vento",
        "Patrick Rothfuss",
        "Fantasia",
        "44.90",
        15,
        "Kvothe conta sua história em uma estalagem, entre magia e mistério.",
    ),
    (
        "It, A Coisa",
        "Stephen King",
        "Terror",
        "46.00",
        12,
        "Um grupo enfrenta um mal antigo que assombra Derry no Maine.",
    ),
    (
        "Drácula",
        "Bram Stoker",
        "Terror",
        "24.90",
        28,
        "O conde Drácula e a chegada do vampirismo à Inglaterra vitoriana.",
    ),
    (
        "Frankenstein",
        "Mary Shelley",
        "Terror",
        "22.00",
        20,
        "Victor Frankenstein cria um ser e enfrenta as consequências morais.",
    ),
    (
        "O Chamado de Cthulhu e Outros Contos",
        "H.P. Lovecraft",
        "Terror",
        "26.50",
        18,
        "Contos de horror cósmico que influenciaram gerações de autores.",
    ),
    (
        "1808",
        "Laurentino Gomes",
        "História",
        "54.90",
        10,
        "A chegada da família real portuguesa ao Brasil e suas consequências.",
    ),
    (
        "1822",
        "Laurentino Gomes",
        "História",
        "52.90",
        11,
        "Os bastidores da Independência do Brasil e de dom Pedro I.",
    ),
    (
        "Sapiens: Uma Breve História da Humanidade",
        "Yuval Noah Harari",
        "História",
        "48.00",
        25,
        "Da revolução cognitiva às sociedades globais do século XXI.",
    ),
    (
        "Brasil: Uma Biografia",
        "Lilia Moritz Schwarcz e Heloisa M. Starling",
        "História",
        "59.90",
        8,
        "Síntese historiográfica do Brasil republicano e imperial.",
    ),
    (
        "Longa Caminhada até a Liberdade",
        "Nelson Mandela",
        "Biografia",
        "34.90",
        14,
        "Autobiografia do líder sul-africano contra o apartheid.",
    ),
    (
        "Steve Jobs",
        "Walter Isaacson",
        "Biografia",
        "42.90",
        16,
        "Biografia autorizada do cofundador da Apple.",
    ),
    (
        "Elon Musk",
        "Walter Isaacson",
        "Biografia",
        "49.90",
        13,
        "Retrato do empreendedor por trás da Tesla, SpaceX e outras empresas.",
    ),
    (
        "O Poder do Hábito",
        "Charles Duhigg",
        "Autoajuda",
        "36.00",
        30,
        "Como hábitos funcionam e como transformá-los na vida pessoal e corporativa.",
    ),
    (
        "Como Fazer Amigos e Influenciar Pessoas",
        "Dale Carnegie",
        "Autoajuda",
        "28.90",
        40,
        "Clássico sobre relações humanas e comunicação eficaz.",
    ),
    (
        "A Coragem de Ser Imperfeito",
        "Brené Brown",
        "Autoajuda",
        "32.50",
        22,
        "Reflexões sobre vulnerabilidade, vergonha e pertencimento.",
    ),
    (
        "Clean Code",
        "Robert C. Martin",
        "Técnico",
        "89.90",
        9,
        "Boas práticas para escrever código legível e sustentável.",
    ),
    (
        "O Programador Pragmático",
        "Andrew Hunt e David Thomas",
        "Técnico",
        "79.90",
        11,
        "Guia de atitudes e abordagens para desenvolvedores de software.",
    ),
    (
        "Introdução aos Algoritmos",
        "Thomas H. Cormen et al.",
        "Técnico",
        "199.00",
        6,
        "Referência acadêmica em algoritmos e estruturas de dados.",
    ),
    (
        "O Pequeno Príncipe",
        "Antoine de Saint-Exupéry",
        "Infantil",
        "19.90",
        50,
        "Fábula poética sobre amizade, perda e responsabilidade.",
    ),
    (
        "Matilda",
        "Roald Dahl",
        "Infantil",
        "21.90",
        32,
        "Menina extraordinária enfrenta a diretora Trunchbull na escola.",
    ),
    (
        "A Menina que Roubava Livros",
        "Markus Zusak",
        "Infantil",
        "29.90",
        24,
        "Liesel em Munique durante a Segunda Guerra e o poder das palavras.",
    ),
    (
        "O Menino Maluquinho",
        "Ziraldo",
        "Infantil",
        "24.50",
        28,
        "As travessuras e a imaginação do menino maluquinho.",
    ),
    (
        "Cem Anos de Solidão",
        "Gabriel García Márquez",
        "Romance",
        "41.90",
        17,
        "Saga da família Buendía em Macondo, marco do realismo mágico.",
    ),
    (
        "1984",
        "George Orwell",
        "Ficção Científica",
        "27.00",
        29,
        "Distopia sobre vigilância totalitária e controle da linguagem.",
    ),
    (
        "Orgulho e Preconceito",
        "Jane Austen",
        "Romance",
        "26.00",
        23,
        "Elizabeth Bennet, Mr. Darcy e as convenções da Inglaterra georgiana.",
    ),
    (
        "A Rua dos Cataventos",
        "Mário Quintana",
        "Poesia",
        "29.90",
        15,
        "Eles passarão... Eu passarinho! Primeiro livro de sonetos de Mário Quintana, publicado em 1940.",
    ),
    (
        "Caderno de Hinos",
        "Mário Quintana",
        "Poesia",
        "24.90",
        20,
        "Se as coisas são inatingíveis... ora! Não é motivo para não querê-las... Que tristes seriam os caminhos se não fora a presença distante das estrelas.",
    ),
    (
        "Apontamentos de História Sem Importância",
        "Mário Quintana",
        "Poesia",
        "34.90",
        10,
        "O tempo é um ponto de vista. Velho é quem é um dia mais velho que a gente. Pensamentos sobre o tempo, a infância e o cotidiano.",
    ),
]
