"""Schema completo com imagens

Revision ID: 275944bf37ec
Revises: 
Create Date: 2026-04-23 22:46:41.488680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275944bf37ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
