"""Add headline and bio to user

Revision ID: 38c3de7c8151
Revises: b19c2a44f201
Create Date: 2026-04-29 09:37:21.305593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c3de7c8151'
down_revision = 'b19c2a44f201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leitura_criado_em'))
        batch_op.drop_index(batch_op.f('ix_leitura_leitor_id'))
        batch_op.drop_index(batch_op.f('ix_leitura_livro_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('headline')

    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leitura_livro_id'), ['livro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leitura_leitor_id'), ['leitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leitura_criado_em'), ['criado_em'], unique=False)

    # ### end Alembic commands ###
