"""Add order and order_item models

Revision ID: a5e66ff3117b
Revises: 38c3de7c8151
Create Date: 2026-04-29 10:13:18.759154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e66ff3117b'
down_revision = '38c3de7c8151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leitor_id', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('endereco_rua', sa.String(length=200), nullable=True),
    sa.Column('endereco_numero', sa.String(length=20), nullable=True),
    sa.Column('endereco_bairro', sa.String(length=100), nullable=True),
    sa.Column('endereco_cidade', sa.String(length=100), nullable=True),
    sa.Column('endereco_estado', sa.String(length=2), nullable=True),
    sa.Column('endereco_cep', sa.String(length=20), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['leitor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_pedido')
    op.drop_table('pedido')
    # ### end Alembic commands ###
